# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shituation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lyrics', models.TextField()),
                ('youtube', models.URLField()),
            ],
        ),
    ]
