# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shituation', '0004_live_livevideo_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
