# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shituation', '0006_bands_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 27, 22, 4, 46, 467201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='song',
            name='demo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='shituation.Demo'),
        ),
    ]
