# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shituation', '0007_auto_20161228_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='demo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_demo', to='shituation.Demo'),
        ),
        migrations.AddField(
            model_name='post',
            name='live',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_live', to='shituation.Live'),
        ),
        migrations.AlterField(
            model_name='bands',
            name='live',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band', to='shituation.Live'),
        ),
        migrations.AlterField(
            model_name='livevideo',
            name='live',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liveVideo', to='shituation.Live'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='live',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='shituation.Live'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 28, 12, 57, 5, 983940, tzinfo=utc)),
        ),
    ]
