# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shituation', '0009_auto_20161228_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shituation.Bands'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shituation.Photos'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shituation.LiveVideo'),
        ),
        migrations.AlterField(
            model_name='livevideo',
            name='live',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liveVideo', to='shituation.Live'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='live',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='shituation.Live'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 30, 18, 35, 6, 126402, tzinfo=utc)),
        ),
    ]
