# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shituation', '0010_auto_20161230_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shituation.Song'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 29, 14, 47, 17, 629467, tzinfo=utc)),
        ),
    ]
