# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shituation', '0011_auto_20170129_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 29, 14, 47, 33, 11347, tzinfo=utc)),
        ),
    ]
